### ISSUE TITLE
Consulta: data historica

### ISSUE THREAD

**Issue by azimut** [Aerolab/acanohayluz#2]
Existe la posibilidad de hacer publico algun dump historico de la db que usa acanohayluz.com.ar? Anonimizada por supuesto. Agegada o no. Se me hace interesante "ver" un timelapse de esa data o que otras cosas hay en el dataset.

**Comment by RobertoGonzalez** [comment]
@azimut Mandame un mail a hey@aerolab.co así te paso el dataset histórico con todos los reportes. No lo tenemos lo suficientemente procesado como para publicarlo acá. Abrazo!
