### ISSUE TITLE
 ZONAS_SELECCIONABLES is not defined

### ISSUE THREAD

**Issue by corcaribe** [Aerolab/acanohayluz#4]
Buenas tardes, espero que se encuentren muy bien. Ante todo los felicito por este desarrollo y por haber publicado el código para que sea utilizado, mejorado y compartido.

Les escribo desde Venezuela. Como todos saben estamos pasando por una situación compleja y considero que sería de gran ayuda adaptar el código a nuestras zonas.

Seguí las instrucciones y logré montar la base de datos y posicionar el mapa en la ciudad de Guatire donde estoy haciendo las pruebas pero aún no logro que funciones la búsqueda ni el dibujo de las zonas.

Estos son los datos que estoy utilizando en las tablas

Tabla zona:
# id, nombre, poligono, lat, long, slug, estado, estado_ultimo_tweet, civilizacion, bound_sw_long, bound_sw_lat, bound_ne_long, bound_ne_lat, fecha_update_reportes, seleccionable, fecha_update_estado
'1', 'Guatire', '[[[10.495491892912016,-66.55320167541504],[10.465023915619811,-66.55577659606934],[10.458018389341188,-66.54006958007812],[10.492200483032397,-66.54152870178223]]]', '10.4757', '-66.5487', 'guatire', '1', '0', '1', '-66.562845', '10.46593', '-66.534555', '10.48547', '2019-03-17 16:55:58', '0', '2019-03-17 14:44:21'

Tabla aliaszona:
# id, zona_id, nombre
'1', '1', 'Guatire'

Este es uno de los errores que me aparece en la consola del navegador. 

scripts.min.js:223 Uncaught ReferenceError: ZONAS_SELECCIONABLES is not defined
    at setup_selector_zona (scripts.min.js:223)
    at init_mapa (scripts.min.js:344)
    at desktop_setup (scripts.min.js:532)
    at HTMLDocument.<anonymous> (scripts.min.js:564)
    at c (jquery.min.js:4)
    at Object.fireWith [as resolveWith] (jquery.min.js:4)
    at Function.ready (jquery.min.js:4)
    at HTMLDocument.q (jquery.min.js:4)
setup_selector_zona @ scripts.min.js:223
init_mapa @ scripts.min.js:344
desktop_setup @ scripts.min.js:532
(anonymous) @ scripts.min.js:564
c @ jquery.min.js:4
fireWith @ jquery.min.js:4
ready @ jquery.min.js:4
q @ jquery.min.js:4

Gracias de antemano por la colaboración prestada

**Comment by RobertoGonzalez** [comment]
@corcaribe Por lo que recuerdo de la app, al agregar una nueva zona tenés que correr procesar_nuevas_zonas.php y cachear_zonas.php. 
En particular cachear_zonas.php genera static/zonas.js, que es el archivo que calculo te está faltando.

Saludos!
